In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import linregress
import scipy.stats as st

In [9]:
df_2019 = pd.read_csv('Resources/2019.csv')

In [10]:
df_2019.head()

,Country,Year,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family/Social Support,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity
0,Finland,2019,1,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,Denmark,2019,2,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,Norway,2019,3,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,Iceland,2019,4,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,Netherlands,2019,5,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [13]:
column = ['Economy (GDP per Capita)',
        'Family/Social Support',
        'Health (Life Expectancy)',
        'Freedom',
        'Trust (Government Corruption)',
        'Generosity'
          ]
pd.read_csv(df_2019,delimiter =';',names = column)

ValueError: Invalid file path or buffer object type: <class 'set'>

In [7]:

corrMatrix = df.corr()
print (corrMatrix)

,Year,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family/Social Support,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity
Year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Happiness Rank,NaN,1.000000,-0.989096,-0.801947,-0.767465,-0.787411,-0.546606,-0.047993,-0.351959
Happiness Score,NaN,-0.989096,1.000000,0.793883,0.777058,0.779883,0.566742,0.075824,0.385613
Economy (GDP per Capita),NaN,-0.801947,0.793883,1.000000,0.754906,0.835462,0.379079,-0.079662,0.298920
Family/Social Support,NaN,-0.767465,0.777058,0.754906,1.000000,0.719009,0.447333,-0.048126,0.181899
Health (Life Expectancy),NaN,-0.787411,0.779883,0.835462,0.719009,1.000000,0.390395,-0.029511,0.295283
Freedom,NaN,-0.546606,0.566742,0.379079,0.447333,0.390395,1.000000,0.269742,0.438843
Trust (Government Corruption),NaN,-0.047993,0.075824,-0.079662,-0.048126,-0.029511,0.269742,1.000000,0.326538
Generosity,NaN,-0.351959,0.385613,0.298920,0.181899,0.295283,0.438843,0.326538,1.000000

In [ ]:
corr_matrix.corr()