# Data Cleaning

In [1]:
import pandas as pd

In [2]:
df_2015_raw = pd.read_csv('Resources/2015_raw.csv')
df_2016_raw = pd.read_csv('Resources/2016_raw.csv')
df_2017_raw = pd.read_csv('Resources/2017_raw.csv')
df_2018_raw = pd.read_csv('Resources/2018_raw.csv')
df_2019_raw = pd.read_csv('Resources/2019_raw.csv')

In [3]:
df_2015_raw.info()
df_2015_raw.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        158 non-null    object
 1   Region                         158 non-null    object
 2   Happiness Rank                 158 non-null    int64
 3   Happiness Score                158 non-null    float64
 4   Standard Error                 158 non-null    float64
 5   Economy (GDP per Capita)       158 non-null    float64
 6   Family                         158 non-null    float64
 7   Health (Life Expectancy)       158 non-null    float64
 8   Freedom                        158 non-null    float64
 9   Trust (Government Corruption)  158 non-null    float64
 10  Generosity                     158 non-null    float64
 11  Dystopia Residual              158 non-null    float64
dtypes: float64(9), int64(1), object(2)
memory usage: 14.9+ KB

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [4]:
df_2015_raw = df_2015_raw[["Country", "Happiness Rank", "Happiness Score", "Economy (GDP per Capita)", "Family", "Health (Life Expectancy)", "Freedom", "Trust (Government Corruption)", "Generosity"]]
df_2015_raw["Year"] = "2015"
df_2015_raw = df_2015_raw.rename(columns={"Family":"Family/Social Support"})
df_2015 = df_2015_raw[["Country", "Year", "Happiness Rank", "Happiness Score", "Economy (GDP per Capita)", "Family/Social Support", "Health (Life Expectancy)", "Freedom", "Trust (Government Corruption)", "Generosity"]]
df_2015

,Country,Year,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family/Social Support,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity
0,Switzerland,2015,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678
1,Iceland,2015,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630
2,Denmark,2015,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139
3,Norway,2015,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699
4,Canada,2015,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811
...,...,...,...,...,...,...,...,...,...,...
153,Rwanda,2015,154,3.465,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628
154,Benin,2015,155,3.340,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260
155,Syria,2015,156,3.006,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179
156,Burundi,2015,157,2.905,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727
157,Togo,2015,158,2.839,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681

In [ ]:
df_2015.to_csv("'Resources/2015.csv'")